---
- name: Verfify MachineConfigPool
  block:
  - name: Retrieve all MCP
    kubernetes.core.k8s_info:
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      kind: MachineConfigPool
    register: mcp_list
    no_log: True

  - set_fact:
      msg: "{% for item in mcp_list.resources %} MCP {{item.metadata.name}} Check Status: \n {{ item.status.conditions[0].type }}: {{ item.status.conditions[0].status }}. {{ item.status.conditions[0].message }} \n {{ item.status.conditions[1].type }}: {{ item.status.conditions[1].status }}. {{ item.status.conditions[1].message }} \n {{ item.status.conditions[2].type }}: {{ item.status.conditions[2].status }}. {{ item.status.conditions[2].message }} \n {{ item.status.conditions[3].type }}: {{ item.status.conditions[3].status }}. {{ item.status.conditions[3].message }} \n {{ item.status.conditions[4].type }}: {{ item.status.conditions[4].status }}. {{ item.status.conditions[4].message }} \n {% endfor %}"
      name: "MCP Check"
      tname: "MCP Check"
    no_log: True
  
  - name: Assert that MCP healthchecks are passing
    assert:
      quiet: yes
      that:
        - "{{ item.status.degradedMachineCount != '0' }}" 
        - "{{ item.status.unavailableMachineCount != '0' }}" 
        - "{{ item.status.updatedMachineCount == item.status.machineCount }}" 
      fail_msg: "The MCP Health Check failed."
      success_msg: "MCP is Healthy"
    with_items: "{{ mcp_list.resources }}"
    register: result
    no_log: True

  - name: MCP Check Results
    blockinfile:
      path: "{{ result_file }}"
      marker: "              "
      insertafter: "######################### MCP Check #########################"
      block: |
        MCP Check Passed 

    delegate_to: localhost
    no_log: True
